'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'未知').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>n==null?'未知':Number(n).toLocaleString('zh-CN',{maximumFractionDigits:2}), pct=n=>n==null?'—':num(n*100)+'%', safe=u=>{if(typeof u!=='string'||!u)return null;try{let x=new URL(u,location.href);return ['https:','http:'].includes(x.protocol)?x.href:null}catch{return null}};
// Translate presentation labels only; manifests, identifiers and recorded evidence stay unchanged.
const statusNames={queued:'等待运行',initializing:'初始化中',running:'运行中',paused:'已暂停',failed:'失败',complete:'已完成',invalid:'无效'};
const verificationNames={local_sha256:'仅本地 SHA 已核验',remote_sha256:'远端 SHA 已核验',bundle_remote_sha256:'归档包远端 SHA 已核验',none:'尚未核验'};
const viewNames={head:'头部相机',left_wrist:'左腕相机',right_wrist:'右腕相机'};
const reasonNames={'original':'首次尝试','original frozen experiment imported after archive completion':'原始冻结实验，归档完成后导入'};
const limitationNames={
  'This is one historical run; a complete comparable round requires independent coverage and evidence validation.':'这是单条历史记录；完整可比轮次还需核对任务覆盖与证据。',
  'Historical action limit is unknown or unspecified; null must not be interpreted as zero, 20, or an unlimited policy.':'历史动作上限未知或未注明；空值不表示零步、20 步或不限步数。',
  'Asset identity is the frozen original manifest SHA; direct source asset bytes were not available for an independent hash check during this export.':'场景标识采用原冻结清单的 SHA；本次导出未取得场景源文件，无法再次独立核验其字节。',
  'Some historical source lock entries are no longer present or differ; each is listed explicitly. Selected policy SHA verified.':'部分历史源码锁定文件缺失或已变化，已逐项列明；本次所选动作策略的 SHA 已核验。',
  'Only the archived terminal and last native ACK snapshot are exported for this run; full per-control command/observation trace remains available.':'本次导出包含归档终态和最后一次原生动作回执快照；逐控制步的命令与观测轨迹另行保留。',
  'This representative sample is not a complete comparable round and has no overall benchmark score.':'当前代表性样例未覆盖完整可比轮次，不提供基准总分。',
  'Native internal identities are pseudonymized; raw account/session journals are retained only by the source owner.':'原生内部标识已替换为匿名标识；原始账号与会话日志仅由来源方保留。',
  'Public note/reason is original visible tool text, not hidden model reasoning.':'公开说明来自原始工具可见文本，不含模型私有推理。',
  'Historical GPU model, driver, full dependency versions, and source Git commit were not captured in the per-run imported records; null is intentional.':'导入的历史记录未包含 GPU 型号、驱动、完整依赖版本及源码 Git 提交，因此这些字段保留为空。',
  'Official scene asset bytes are not redistributed; scene identity is a SHA256.':'不再分发官方场景资产文件，使用 SHA-256 标识场景。',
  'This case ran on Sim5.1; the selected Astra baseline and coor case ran on Sim6. The comparison is not isolated to algorithm alone.':'本次实验使用 Sim5.1；所选 Astra 基线及 coor 实验使用 Sim6，比较差异并非仅来自算法。'
};
const label=(map,value)=>map[value]??value;
let db={runs:[],statistics:{groups:[]}},filtered=[];
function link(u,title){const x=safe(u);return x?`<a href="${esc(x)}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`:`<span class="muted">${esc(title)} · 暂不可用</span>`}
function storage(a){return a.storage||{}}function landing(a){return storage(a).landing_url||storage(a).download_url||null}function download(a){return storage(a).download_url||storage(a).landing_url||null}
function costs(r){const a=r.costs?.attempts||[];return {known:a.reduce((s,x)=>s+(x.input_tokens??0)+(x.output_tokens??0),0),cached:a.reduce((s,x)=>s+(x.cached_input_tokens??0),0),unknown:a.filter(x=>!x.usage_known||x.input_tokens==null||x.output_tokens==null).length}}
function options(id,values,names={}){let e=$(id);[...new Set(values.filter(x=>x!=null))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).forEach(x=>{let o=document.createElement('option');o.value=x;o.textContent=label(names,x);e.append(o)})}
function render(){const q=$('#query').value.toLowerCase();filtered=db.runs.filter(r=>(!$('#algorithm').value||r.algorithm.algorithm_id==$('#algorithm').value)&&(!$('#protocol').value||r.protocol.id==$('#protocol').value)&&(!$('#seed').value||r.scene.official_seed==$('#seed').value)&&(!$('#layout').value||r.scene.layout_ordinal==$('#layout').value)&&(!$('#status').value||r.status==$('#status').value)&&($('#legacy').checked||r.protocol.action_limit!=null)&&(!q||[r.scene.task,r.run_id,r.attempt.contributor_id,'attempt '+r.attempt.index,'尝试 '+r.attempt.index].join(' ').toLowerCase().includes(q)));
$('#count').textContent=`显示 ${filtered.length} / ${db.runs.length} 次实验`;
$('#rows').innerHTML=filtered.map(r=>{let c=costs(r);return `<tr><td><strong>${esc(r.scene.task)}</strong><small>${esc(r.algorithm.algorithm_id)} · ${esc(r.algorithm.version)}</small><small>${esc(r.protocol.id)}</small></td><td><strong>${esc(r.scene.official_seed)} / ${esc(r.scene.layout_ordinal)}</strong><small>种子 / 布局 · 轮次 ${esc(r.scene.round_index)}</small><small>资产 ${esc(r.scene.asset_sha256?.slice(0,12))}…</small></td><td><strong>#${esc(r.attempt.index)}</strong><small>${esc(r.attempt.contributor_id)}</small><small>${esc(label(reasonNames,r.attempt.reason||'original'))}</small></td><td><span class="pill ${r.outcome?.episode_complete?'':'warn'}">${esc(label(statusNames,r.status))}</span><div class="score">${r.outcome?.score==null?'—':num(r.outcome.score*100)}<small style="display:inline;font-size:10px"> / 100</small></div><small>${r.outcome?.episode_complete?'原生终态已核验':'尚无已核验的原生终态'}</small></td><td><strong>${num(r.outcome?.control_steps)} 个控制步</strong><small>${num(r.outcome?.model_decisions)} 次决策 · ${num(r.outcome?.actual_responses)} 次响应</small><small>${num(c.known)} 个已知 token${c.unknown?'，另有未知用量':''}</small><small>其中缓存输入：${num(c.cached)}</small></td><td><button data-run="${esc(r.run_id)}">查看详情 ↗</button><small>${r.artifacts?.length||0} 个文件</small><small>${r.artifacts?.some(a=>storage(a).verification==='remote_sha256')?'已有远端 SHA 核验记录':'远端核验待完成'}</small></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">没有符合筛选条件的实验。</td></tr>';
document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>detail(db.runs.find(r=>r.run_id===b.dataset.run)));
renderComparison();}
function renderComparison(){const ids=new Set(filtered.map(r=>r.algorithm.algorithm_id));$('#comparison').innerHTML=(db.statistics?.groups||[]).filter(g=>ids.has(g.algorithm_id)).map(g=>{let c=g.cumulative||{},tasks=c.tasks||{},panels=g.panels||[];return `<article class="comparison-card"><div class="comparison-head"><div><h3>${esc(g.algorithm_id)}</h3><span class="muted">${esc(g.protocol_id)} · 可比组 ${esc(g.group_id?.slice(0,10))}</span></div><span class="pill warn">${c.overall_score==null&&c.score==null?'覆盖不完整 · 不计总分':'覆盖完整'}</span></div><p class="small">${panels.map(p=>`种子 ${p.official_seed}，布局 ${p.layout_ordinal}，轮次 ${p.round_index}：${esc(p.complete?'已完成':'未完成')} · ${num(p.valid??p.completed_tasks??p.observed_tasks??p.task_count)} 个任务`).join('<br>')||'尚未登记完整的官方轮次。'}</p><div class="coverage-bar"><span style="width:${Math.min(100,(c.task_coverage||0)/54*100)}%"></span></div><div class="task-stats">${Object.entries(tasks).filter(([,s])=>s.n>0).map(([t,s])=>`<div class="task-stat"><strong>${esc(t)}</strong><span>样本数 ${num(s.n)} · 均值 ${num(s.mean)+'%'} · 样本标准差 ${s.n<2?'未定义（n<2）':num(s.sample_sd)+'%'}<br>范围 ${num(s.min)+'%'}–${num(s.max)+'%'} · 样本方差 ${num(s.sample_variance)}</span></div>`).join('')}</div><details><summary>覆盖范围、缺失项与全部尝试消耗（原始 JSON）</summary><pre>${esc(JSON.stringify({panels:g.panels,cumulative:c,costs:g.costs},null,2))}</pre></details></article>`}).join('')||'<p class="empty">暂无可比统计分组。</p>'}
function mediaCards(artifacts,isDemo){const a=artifacts.filter(x=>/video|demo/i.test(x.kind)&& (isDemo?/demo|rationale/i.test(x.kind):!/demo|rationale/i.test(x.kind)));return `<h3>${isDemo?'公开说明演示':'原生三视角录像'}</h3><div class="video-grid">${a.map(v=>`<div class="video-card"><h4>${esc(v.view?label(viewNames,v.view):isDemo?'公开说明演示':v.path.split('/').pop())}</h4>${storage(v).playback_url&&safe(storage(v).playback_url)?`<video controls preload="metadata" src="${esc(safe(storage(v).playback_url))}" aria-label="${esc(v.view?label(viewNames,v.view):isDemo?'公开说明演示':v.kind)}"></video>`:'<div class="video-unavailable">尚未核验直连播放。<br>请使用云盘预览或下载链接。</div>'}<p>${link(download(v),'下载 / 云盘预览')}</p><small class="muted">${num(v.bytes/1048576)} MiB · ${esc(label(verificationNames,storage(v).verification||'local_sha256'))}</small></div>`).join('')||'<p class="muted">本清单中没有对应的媒体文件。</p>'}</div>`}
async function detail(r){let c=costs(r);$('#detail-title').textContent=r.scene.task+' · '+r.algorithm.algorithm_id;$('#detail-body').innerHTML=`<div class="details-grid"><div><small>运行标识</small>${esc(r.run_id)}<br>尝试 ${esc(r.attempt.index)} · ${esc(label(reasonNames,r.attempt.reason))}</div><div><small>场景</small>种子 ${r.scene.official_seed} / 布局 ${r.scene.layout_ordinal} / 轮次 ${r.scene.round_index}<br>${esc(r.scene.asset_path)}</div><div><small>算法 / 客户端</small>${esc(r.algorithm.model)} · 推理强度 ${esc(r.algorithm.reasoning_effort)}<br>Codex ${esc(r.algorithm.codex_client_version)} · 每次动作前缀上限 ${num(r.protocol.action_limit)}</div><div><small>实际环境</small>${esc(r.environment.simulator_version)}<br>${esc(r.environment.gpu==null?'GPU 未记录':typeof r.environment.gpu==='object'?JSON.stringify(r.environment.gpu):r.environment.gpu)} · 驱动 ${esc(r.environment.driver)}</div><div><small>原生结果</small>${esc(label(statusNames,r.status))} · ${pct(r.outcome.score)}<br>${num(r.outcome.control_steps)} 个控制步 / ${num(r.outcome.model_decisions)} 次决策 / ${num(r.outcome.actual_responses)} 次响应</div><div><small>全部付费尝试</small>${num(c.known)} 个已知输入与输出 token<br>${num(c.cached)} 个缓存输入 token（已计入上方总量）<br>${num(c.unknown)} 条未知用量记录</div></div><div class="notice">公开说明为模型当时记录的工具可见文本，保留原文，不包含私有推理。 ${esc((r.audit?.limitations||[]).map(s=>label(limitationNames,s)).join(' '))}</div>${mediaCards(r.artifacts||[],false)}${mediaCards(r.artifacts||[],true)}<h3>动作与公开说明（原文）</h3><div id="timeline" class="timeline"><p class="muted">请使用下方公开审计记录或轨迹下载链接。在线时间线需可访问的 JSON 文件及 CORS 跨域支持。</p></div><h3>文件与核验</h3><ul class="artifact-list">${(r.artifacts||[]).map(a=>`<li><div>${link(download(a),a.path+(storage(a).bundle_member?'［归档包内文件］':''))}<br><code>SHA-256 ${esc(a.sha256)}</code></div><span>${num(a.bytes)} 字节</span></li>`).join('')}</ul><details><summary>环境、版本、消耗记录与原生证据清单（原始 JSON）</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`;$('#detail').showModal();
const timeline=(r.artifacts||[]).find(a=>/timeline|public_audit|trajectory/i.test(a.kind)&&(storage(a).timeline_url||storage(a).json_url));if(timeline){try{const res=await fetch(safe(storage(timeline).timeline_url||storage(timeline).json_url));if(!res.ok)throw Error();let t=await res.json(),events=Array.isArray(t)?t:t.events||t.steps||[];$('#timeline').innerHTML=events.slice(0,2000).map(e=>`<div><small>决策 ${esc(e.policy_step??e.control_step??e.step??e.index??'事件')} · 控制步 ${esc(e.control_start)}→${esc(e.control_end)} · ${esc(e.tool)}</small><br>${esc(e.public_note??e.note??e.instruction??JSON.stringify(e))}<details><summary>动作参数与原生反馈（原文）</summary><pre>${esc(JSON.stringify(e.arguments??{},null,2))}</pre><p>${esc(e.feedback)}</p></details></div>`).join('')}catch{/* Keep explicit download fallback. */}}
}
$('#close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});document.querySelectorAll('.filters input,.filters select,#legacy').forEach(x=>x.addEventListener('input',render));$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(filtered,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='robodojo-filtered-manifests.json';a.click();URL.revokeObjectURL(url)};
async function boot(){try{const res=await fetch('data/index.json');if(!res.ok)throw Error(`HTTP ${res.status}`);db=await res.json();options('#algorithm',db.runs.map(r=>r.algorithm.algorithm_id));options('#protocol',db.runs.map(r=>r.protocol.id));options('#seed',db.runs.map(r=>r.scene.official_seed));options('#layout',db.runs.map(r=>r.scene.layout_ordinal));options('#status',db.runs.map(r=>r.status),statusNames);const total=db.runs.reduce((s,r)=>s+costs(r).known,0);$('#metrics').innerHTML=[[db.runs.length,'已记录实验'],[new Set(db.runs.map(r=>r.algorithm.algorithm_id)).size,'已登记版本的算法'],[new Set(db.runs.map(r=>r.scene.asset_sha256)).size,'不同的已核验场景资产'],[num(total),'已知 token 总量 · 含缓存输入']].map(([v,k])=>`<div class="metric"><strong>${esc(v)}</strong><span>${k}</span></div>`).join('');$('#updated').textContent='索引更新时间：'+new Date(db.generated_at).toLocaleString('zh-CN');if(db.repository_url){$('#repo-link').href=db.repository_url.replace(/\/$/,'')+'/blob/main/docs/GETTING_STARTED_zh-CN.md';$('#guide').href=$('#repo-link').href}render()}catch(e){$('#metrics').textContent='结果索引暂不可用';$('#warning').hidden=false;$('#warning').textContent='无法加载结果索引。请通过 HTTP 服务访问此目录，或重新生成 web/data/index.json。'+e.message}}
boot();
